name: BareBonesChat
version: '${project.version}'
main: me.dash.bareboneschat.BareBonesChat
api-version: 1.19
authors: [ Dashersack ]
description: A lightweight chat plugin.
softdepend: [ Vault ]
commands:
  message:
    description: Privately send a message to a player.
    usage: </command> <player> <message>
    aliases: [msg, whisper]
  reply:
    description: Reply to a private message.
    usage: </command> <message>
    aliases: [r]
  messagespy:
    description: Toggle the ability to see private other players' messages.
    usage: </command>
    aliases: [mspy, spy]
  bbchat:
    description: BareBonesChat commands.
    usage: /<command> [help]
    aliases: [ bareboneschat, bbc ]
permissions:
  bbchat.message:
    description: Allows access to the message command.
    default: true
  bbchat.reply:
    description: Allows access to the reply command.
    default: true
  bbchat.messagespy:
    description: Allows access to the message spy command.
    default: false
  bbchat.help:
    description: Allows access to the help subcommand.
    default: true